apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-depl
  labels: 
    app: post
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
      - name: post
        image: vincentdevweb/post:latest
        resources:
          limits:
            memory: "258Mi"
            cpu: "1000m"
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: post-srv
spec:
  type: NodePort
  selector:
    app: post
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      name: post